version: "3.0"
services: 
  postgres:
    image: postgres:14.3-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume: